# Generated by Django 4.1.7 on 2024-01-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b', models.CharField(max_length=100, null=True)),
                ('c', models.CharField(max_length=100, null=True)),
                ('d', models.CharField(max_length=100, null=True)),
                ('e', models.CharField(max_length=100, null=True)),
                ('f', models.CharField(max_length=100, null=True)),
                ('h', models.CharField(max_length=100, null=True)),
                ('i', models.CharField(max_length=100, null=True)),
                ('j', models.CharField(max_length=100, null=True)),
                ('k', models.CharField(max_length=100, null=True)),
                ('g', models.CharField(max_length=100, null=True)),
                ('l', models.CharField(max_length=100, null=True)),
                ('m', models.CharField(max_length=100, null=True)),
                ('n', models.CharField(max_length=100, null=True)),
                ('o', models.CharField(max_length=100, null=True)),
                ('p', models.CharField(max_length=100, null=True)),
                ('q', models.CharField(max_length=100, null=True)),
                ('r', models.CharField(max_length=100, null=True)),
                ('s', models.CharField(max_length=100, null=True)),
                ('out', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
            ],
        ),
    ]
